navbar: 
  sitename: 
  menu: 
    - name: 首页
      url: /
    - name: 标签
      url: /tags/
    - name: 归档
      url: /archives/
  sticky: true

cover: 
  sitename: 
  description: 

meta:
  title: Post
  author:
    name: xfqwdsj
    url: https://blog.xfqlittlefan.xyz
  date:
    title: ''
    format: 'YYYY-MM-DD'
  updated:
    title: ''
    format: 'YYYY-MM-DD'
  thumbnail: 
    enable: false
    default: 
  expire: 
    enable: true
    duration: 120
  auto_excerpt: 
    enable: true
    length: 150
  toc: 
    enable: true
    list_number: true
  copyright: 
    enable: true
    custom_text: 

footer:
  copyright_since: 2022

lazyload:
  enable: true
  onlypost: false
  loadingImage: 

search:
  enable: true

note: true

fold: 
  enable: true
  motion: true

fancybox: 
  enable: true
  auto: true

back_to_top: true